const abc = {
    "app_id": "com.mojang.minecraftpe",
    "canonical_country": "US",
    "name": "Minecraft",
    "publisher_name": "Mojang",
    "publisher_id": "Mojang",
    "humanized_name": "Minecraft",
    "icon_url": "https://play-lh.googleusercontent.com/VSwHQjcAttxsLE47RuS4PqpC4LT7lCoSjE7Hx5AW_yCxtDvcnsHHvm5CTuL5BPN-uRTP=s150",
    "os": "android",
    "id": "com.mojang.minecraftpe",
    "appId": "com.mojang.minecraftpe",
    "icon": "https://play-lh.googleusercontent.com/VSwHQjcAttxsLE47RuS4PqpC4LT7lCoSjE7Hx5AW_yCxtDvcnsHHvm5CTuL5BPN-uRTP=s150",
    "iconUrl": "https://play-lh.googleusercontent.com/VSwHQjcAttxsLE47RuS4PqpC4LT7lCoSjE7Hx5AW_yCxtDvcnsHHvm5CTuL5BPN-uRTP=s150",
    "url": "https://play.google.com/store/apps/details?hl=en&id=com.mojang.minecraftpe",
    "categories": [
        "game_arcade",
        "game"
    ],
    "valid_countries": [
        "US",
        "AU",
        "BR",
        "CA",
        "FR",
        "DE",
        "GB",
        "JP",
        "KR",
        "MX",
        "ES",
        "IT",
        "RU",
        "DZ",
        "AO",
        "AR",
        "AT",
        "AZ",
        "BH",
        "BY",
        "BE",
        "BM",
        "BG",
        "CL",
        "CO",
        "CR",
        "HR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "EC",
        "EG",
        "SV",
        "FI",
        "GH",
        "GR",
        "GT",
        "HK",
        "HU",
        "IN",
        "ID",
        "IE",
        "IL",
        "KZ",
        "KE",
        "KW",
        "LB",
        "LT",
        "LU",
        "MO",
        "MY",
        "MT",
        "NL",
        "NZ",
        "NG",
        "NO",
        "OM",
        "PK",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "QA",
        "RO",
        "SA",
        "RS",
        "SG",
        "SK",
        "SI",
        "ZA",
        "LK",
        "SE",
        "CH",
        "TW",
        "TH",
        "TN",
        "TR",
        "UA",
        "AE",
        "UY",
        "UZ",
        "VE",
        "VN",
        "BO",
        "KH",
        "EE",
        "LV",
        "NI",
        "PY",
        "GE",
        "IQ",
        "LY",
        "MA",
        "MZ",
        "YE"
    ],
    "app_view_url": "/android/us/mojang/app/minecraft/com.mojang.minecraftpe/",
    "publisher_profile_url": "/android/publisher/mojang/Mojang",
    "release_date": "2011-08-15T00:00:00Z",
    "updated_date": "2021-08-06T00:00:00Z",
    "in_app_purchases": true,
    "shows_ads": null,
    "buys_ads": null,
    "rating": 4.595068,
    "price": 7.49,
    "global_rating_count": 4253211,
    "rating_count": 4253211,
    "rating_count_for_current_version": 4253211,
    "rating_for_current_version": 4.595068,
    "version": "1.17.11.01",
    "apple_watch_enabled": null,
    "apple_watch_icon": null,
    "imessage_enabled": null,
    "imessage_icon": null,
    "humanized_worldwide_last_month_downloads": {
        "downloads": 300000,
        "downloads_rounded": 300,
        "prefix": null,
        "string": "300k",
        "units": "k"
    },
    "humanized_worldwide_last_month_revenue": {
        "prefix": "$",
        "revenue": 4000000,
        "revenue_rounded": 4,
        "string": "$4m",
        "units": "m"
    },
    "bundle_id": "com.mojang.minecraftpe",
    "support_url": "http://help.mojang.com",
    "website_url": "http://help.mojang.com",
    "privacy_policy_url": "https://privacy.microsoft.com/en-us/privacystatement",
    "eula_url": null,
    "publisher_email": "help@minecraft.net",
    "publisher_address": "Mojang\nMaria Skolgata 83\n118 53\nStockholm\nSweden",
    "publisher_country": "Sweden",
    "feature_graphic": "https://play-lh.googleusercontent.com/yAtZnNL-9Eb5VYSsCaOC7KAsOVIJcY8mpKa0MoF-0HCL6b0OrFcBizURHywpuip-D6Y",
    "short_description": "Millions of crafters have smashed billions of blocks! Now you can join the fun!",
    "advisories": null,
    "content_rating": "Everyone 10+",
    "rank": 1,
    "delta": 0,
    "downloads_revenue_date": "2021-09-04T00:00:00Z"
};